[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winsafe = { version = "0.0.15", features = ["gui", "user"] }

[build-dependencies]
winres = "0.1"
embed-resource = "2.1"

